### ISSUE TITLE
Any way to change OpenGOAL-Launcher extraction data folder?

### ISSUE THREAD

**Issue by KainXVIII** [open-goal/launcher#105]
Currently extracted iso data is stored only in c:\Users\my user name\AppData\Roaming\OpenGOAL-Launcher\ but i don't wanna clog precious free ssd space with this..Why it can't be stored in the actual installation folder of OpenGOAL-Launcher?

**Comment by Zedb0T** [comment]
There is an overhaul in the works that claims to fix this issue. https://github.com/open-goal/launcher/pull/104 as far as I can tell.
