### ISSUE TITLE
custom install path settings

### ISSUE THREAD

**Issue by CuddleBear92** [open-goal/launcher#13]
Think we should be able to set the install path of the games in the UI of the launcher and the settings.json file.
We should be able to set either a base path where all games default too or set the path per game like other launchers.

Currently the game gets installed in the roaming appdata directory.

**Comment by RaijinXBlade** [comment]
By chance is this implemented yet? I would certainly appreciate being able to set a secondary HDD as the path for everything instead of my main SSD.
Thanks for the continued work on this project.

**Comment by trippjoe** [comment]
https://discord.com/channels/616186924390023171/731495158217965659/965683694146846760
"you can get the install path at runtime via `tauri::utils::platform::current_exe()?`, no idea about locale, but instead you can probably read the OS language instead" - FabianLars

Saving this as it will come in handy, I think.
