### ISSUE TITLE
UI stuck after updating

### ISSUE THREAD

**Issue by trippjoe** [open-goal/launcher#132]
![image](https://user-images.githubusercontent.com/86533397/182933529-9551942a-3660-40aa-a9ce-afbd226b8ea7.png)

After the user presses "Update Install" and waits for the install, it will return them back to the same screen. For now, users will have to manually restart the application until we fix this.

**Comment by AngryScotsmanGaming** [comment]
Yeah bud when eve using installer trying to save into your original launcher folder it asks do you have permission!?!? apparently most bugs would have been fixed for 1.0.0 no clue why they even giving options to download when is so messed up.... Surely they have testers for this?

**Comment by trippjoe** [comment]
https://github.com/open-goal/launcher/commit/9bf0fa0a4555daa20c93478132c88e3f73d2bf6d

I believe this commit should solve this issue. Would like it tested though.
