### ISSUE TITLE
[mods] Some ideas for an OpenGOAL Mod Manager.

### ISSUE THREAD

**Issue by doctashay** [open-goal/launcher#165]
This is more or less an extension of open-goal/jak-project#386 but will be helpful for keeping track of ideas related to this feature specifically. I've been doing some thinking on this and here's what I've got so far:

The overall goal with this should be to make modifications to OpenGOAL easy and accessible for end-users. I'm looking to programs like Nexus Mod Manager and Mod Organizer for inspiration on approaching OpenGOAL modding.

For the purposes of this program, I'm considering "mods" as any sort of changes to textures, 3D assets and models, code, audio, etc. 

I want it to have a certain set of capabilities:

- It needs to support both Windows and Linux, with the ability to port to macOS once the macOS port is complete. This means I can't use an MFC GUI and will likely need to use a cross-platform GUI lib like Electron or Qt. 

- Broad support for a range of different file types. Whether it's a .txt, .gc, .png, .p3d, etc, our mod manager should be able to support and hotpatch the modded files on top of the vanilla, while also preserving an original copy of the vanilla files so they can be swapped back later.

- Whether a mod simply consists of a single texture swap, or a complete "overhaul", e.g. many different types of modifications to both gameplay code and other assets, it should be as easy as clicking a button to activate a mod, and as easy as another click to deactivate that mod and go back to the vanilla gameplay.

- Conflict detection is a MUST. If you are trying to activate two mods that change the same file, there should be a set of options the user is given to resolve that conflict. 

We could create an archive format for packing these changes up, something like `*.gomod`. 

Once a mod creator has finished their modifications, they should be able to use our packer to create a `.gomod` file containing their changes, which our mod manager then recognizes and lists as an activatable mod. We could create some sort of file that parses metadata about the mod, so that it has a nice clean name, a description of what the mod does, and maybe even a cover image. 

I've started work on this and once I have a semi-functioning GUI I will push the repository to the organization to figure out what's next.

**Comment by xTVaser** [comment]
https://github.com/open-goal/launcher/pull/476
