### ISSUE TITLE
Ability to rescan for requirements

### ISSUE THREAD

**Issue by xTVaser** [open-goal/launcher#166]
There are situations where people are going to change hardware / update drivers / etc and they may need to recheck the requirements that may have failed and now may pass.

**Comment by trippjoe** [comment]
Here is my solution proposal, let me know what you think. On (splash-screen) startup: check the persisted data to see if the  requirements are met, if they aren't met -> run the requirement check, otherwise skip the check.

I also just realized you've got an open PR related to this...

**Comment by xTVaser** [comment]
haha yeah.  In my PR it removes the sidecar completely (hopefully more reliable) and adds a button the user can click to rescan if something intermittent happens or they change hardware.

Though because there is no sidecar, there's probably no issue with just always checking before any installation and removing the settings check, but iirc my PR doesn't go that far yet.  I'm scared to merge that PR without some linux testing
