### ISSUE TITLE
Game-Names arent right.

### ISSUE THREAD

**Issue by TheRealIndianBoi** [open-goal/launcher#172]
As example: Jak and Daxter: The Precursor Legacy ->  Jak and Daxter: The Precursor Legacy™
Jak 2 -> Jak II™: Renegade. (What is about Renegade?)
... etc.

**Comment by TheRealIndianBoi** [comment]
I want to work on that and get some Information. (Working on dev/new-ui.)

**Comment by xTVaser** [comment]
The `Renegade` subtitle was only used on the PAL version of jak 2

You should work off of `main` because `dev/new-ui` has been merged now.

**Comment by TheRealIndianBoi** [comment]
Ah okay thanks for the Info.
