### ISSUE TITLE
Game is launched as a child process

### ISSUE THREAD

**Issue by xTVaser** [open-goal/launcher#18]
re: https://github.com/open-goal/launcher/pull/16#issuecomment-1099198370

I am currently running it with `.execute()` but `spawn()` seems to explicitly be a child process as well.  I saw no way to run an isolated process in the API docs.

**Comment by trippjoe** [comment]
Behaviors to be addressed once we figure out how to keep game child process alive:
- opening the launcher while the game is running
- should we allow another game instance? 
- detect the gk.exe instance and disable play button?

**Comment by trippjoe** [comment]
additional things i didn't consider with the way I've gone about handling this:
the extractor/decomp/comp will keep running if the launcher is closed, meaning we NEED to handle this somehow. maybe we can only let the gk process survive upon killing app process, and kill the rest.
