### ISSUE TITLE
"Unable to reset game settings"

### ISSUE THREAD

**Issue by Zedb0T** [open-goal/launcher#186]
If the json at `file_util::get_user_misc_dir(g_game_version) / "debug-settings.json";` is corrupted, then the launcher is unable to reset the keys and the game is stuck in a state that will not boot until manual intervention is preformed.

**Comment by Zedb0T** [comment]
The suspected cause of https://discord.com/channels/756287461377703987/1101157223780073573/1101157223780073573

**Comment by xTVaser** [comment]
This is expected, the launcher only is concerned with `pc-settings.gc` and resets it by renaming the file, not changing the contents. https://github.com/open-goal/launcher/blob/main/src-tauri/src/commands/game.rs#L45-L68

I think in this case this should be a `jak-project` issue -- if we are unable to successfully read the `debug-settings.json` file, we should trash it -- no clue how the user ended up with a corrupted file but you are correct the file they provided is not a valid json file.
