### ISSUE TITLE
[Feature request] Add a REPL button between "Compile" and "uninstall" buttons

### ISSUE THREAD

**Issue by Zedb0T** [open-goal/launcher#23]
A few ideas that might make things more clear for end users who are tinkering with openGOAL on the launcher version.

- [ ] when installing, copy `goalc.exe` to %appdata%\OpenGOAL-Launcher\goalc.exe and have the button launch it there, so it can find the appropriate `data` folder. 

- [ ] Have this REPL button open the REPL that is in the %appdata% directory.  

- [ ] After install/copying process is complete remove `C:\Program Files\opengoal-launcher\data` directory and `C:\Program Files\opengoal-launcher\goalc.exe` as they are both confusing to end users tinkering with things.

**Comment by trippjoe** [comment]
Working on this now, should have a PR for it tonight.
