### ISSUE TITLE
`cmd` process (REPL on windows) does not terminate when closed / when the launcher is closed

### ISSUE THREAD

**Issue by xTVaser** [open-goal/launcher#252]
![image](https://github.com/open-goal/launcher/assets/13153231/b04059b3-790c-4562-b45f-5ba5dd3aabc4)

**Comment by dallmeyer** [comment]
https://cdn.discordapp.com/attachments/934175504309837864/1118348171748319313/2023-06-13_18-14-30.mp4

**Comment by xTVaser** [comment]
After some testing, this doesn't seem to be the case anymore.  Terminals are spawned as a separate `Windows Terminal` process -- and yes they don't close if the launcher is closed (just like the games, this is fine) but the process terminates properly when the terminal is closed.  I'm able to delete `goalc.exe` to prove it.

**Comment by hypevhs** [comment]
On my install of Windows 10, the `cmd` that launches the REPL stays open even after the REPL window has closed. The introduction of Windows Terminal may have changed the semantics of `cmd \K`.

```
/C      Carries out the command specified by string and then terminates
/K      Carries out the command specified by string but remains
```

So it seems like the solution is to use `cmd \C` to launch the REPL instead.
