### ISSUE TITLE
Make it easy to run a custom one-off `gk` version

### ISSUE THREAD

**Issue by xTVaser** [open-goal/launcher#267]
It'd be nice to make it extremely easy for a user to temporarily launch with a modified `gk`.  This is useful for when we are fixing a bug that a user reports, we can give them a modified executable and they can tell us if the issue has been resolved.

Currently that requires them to shift some files around themselves.

**Comment by fabjan** [comment]
Suggestion: while this override is in effect, make it very obvious to the user in the launcher (which is where I assume the functionality would live) that they are using an extra custom setup so they don't forget after testing and report other issues from their setup which is used by nobody else. And when selecting/downloading a new version the override should probably always be cleared.
