### ISSUE TITLE
Installing launcher without edge installed doesn't work

### ISSUE THREAD

**Issue by trippjoe** [open-goal/launcher#279]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/launcher/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game
- [X] If possible, I've attached the support package zip file to the issue [see how here](https://github.com/open-goal/launcher#asking-for-help)

### Describe the Bug

```
unexpected app error occurred: Runtime(CreateWebview(WebView2Error(WindowsError(Error { code: 0x80070002, message: The system cannot find the file specified. }))))
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: BaseThreadInitThunk
  10: RtlUserThreadStart
```

### How To Reproduce

Install and run the launcher without Edge installed.

How to fix: install Edge, then reinstall launcher. 

What we need to do: Replace the error above with these instructions, if possible.

### Operating System

Windows

### Launcher Version

Latest / *

### Tooling Version

N/A

**Comment by xTVaser** [comment]
Edge missing is not the problem, missing WebView2 is the problem. https://learn.microsoft.com/en-us/deployoffice/webview2-install
> WebView2 Runtime doesn’t install Microsoft Edge (full browser) on the device and doesn’t require Microsoft Edge to be installed on the device.

The installer should install it if it's not in the user's environment:
- https://tauri.app/v1/guides/building/windows#webview2-installation-options
> The installers by default download the WebView2 bootstrapper and executes it if the runtime is not installed.

There was a few bad releases for WebView2 in the recent past which has required some people to manually reinstall it https://opengoal.dev/docs/usage/installation/#windows

But if you can reproduce a problem by removing edge -- then installing the launcher, you should consider opening an issue over on the Tauri side.
