### ISSUE TITLE
Header CSS isn't ideal if the info lines are too long

### ISSUE THREAD

**Issue by xTVaser** [open-goal/launcher#283]
![255346151-830ee347-2f87-4b2f-aab3-9a33f2269f7c](https://github.com/open-goal/launcher/assets/13153231/d348d607-5855-4ad3-ae34-397bcb576c55)

Can cause unsightly overlap / pushing off the close/minimize buttons.

**Comment by fabjan** [comment]
Maybe the flex box needs some changing as well, the buttons should (I think) be aligned at the top, and not centered like the other things.
