### ISSUE TITLE
jak1 background video looks lower-quality

### ISSUE THREAD

**Issue by modusc896d352** [open-goal/launcher#297]
ok, look, i know this is a minor issue in the grand scheme of things but, please, just listen to me. just a sec.

so, as i use the launcher, everything time i select the first game through that launcher, i have to tolerate a blocky-ass shmuch-kahole video with bizarre compression artifacting, probably as a consequence of the video file being encoded in much, MUCH , ***MUCH*** lower quality than i expected.

the video in question is [background-jak1.webm](https://github.com/open-goal/launcher/blob/main/src/assets/videos/background-jak1.webm), btw.

is there any way y'all can just go and, uhhh, kinda sorta "upgrade" the video quality of that one background video, please? my eyes will thank you for this.

**Comment by xTVaser** [comment]
The video is low quality to reduce the download size of the launcher.

There are plans to allow users to use their own video/image files instead of increasing the download size for everyone, so that will probably be the better solution:
- https://github.com/open-goal/launcher/issues/39
- https://github.com/open-goal/launcher/pull/195

**Comment by modusc896d352** [comment]
custom background movies? fine by me i guess, with download sizes being a concern i can kinda understand why it looks the way it does.

i just wish there was a way to improve the video quality of this one, what with all the crossfades that keep happening and all that jazz. and i do mean the default video for jak1. guess i'll just have to close this issue for now.

**Comment by xTVaser** [comment]
Yeah I understand what you were referring to
