### ISSUE TITLE
Detect if user is using massive texture pack

### ISSUE THREAD

**Issue by Zedb0T** [open-goal/launcher#310]
Warn them it's know to potentially cause issues, and if they crash to test with the pack unselected. Maybe add a option on the dialog to unselect all active packs

**Comment by xTVaser** [comment]
I also wonder if there are feasible improvements in the decompiler to give a more explicit error when it fails for these reasons.  Though first it's probably more important to try to mitigate the problem in the first place (lazy-load textures)
