### ISSUE TITLE
Game update didnt go through with PAL ISO!

### ISSUE THREAD

**Issue by OpTicFlutter** [open-goal/launcher#313]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/launcher/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game
- [X] If possible, I've attached the support package zip file to the issue [see how here](https://github.com/open-goal/launcher#asking-for-help)

### Attach Support Package / Log Files (drag and drop)

[opengoal-support-package.zip](https://github.com/open-goal/launcher/files/12505714/opengoal-support-package.zip)

### Describe the Bug

Just wanted to Update the Game to v0.1.40 Tooling Version and almost at the end of the Recompilling or Decompilling it just broke and wouldnt continue.

### How To Reproduce

Just Update to the newest Version.

### Operating System

Windows 10

### Launcher Version

v2.2.1

### Tooling Version

v0.1.40

**Comment by OpTicFlutter** [comment]
NVM i just started it whit Administrator Privileges and now it worked

**Comment by xTVaser** [comment]
The actual problem seems to be related to something breaking with PAL ISOs -- the install process incorrectly assumes ntsc.

**Comment by OpTicFlutter** [comment]
> The actual problem seems to be related to something breaking with PAL ISOs -- the install process incorrectly assumes ntsc.

Never knew that its Version Specific, i just grabed the European Version since it only said, that it needs the .iso of Jak and Daxter 1.

Should i go grab the American Version, that errors like this dont happen anymore?

**Comment by ManDude** [comment]
No. You should just wait for a fix.

**Comment by xTVaser** [comment]
it will be fixed by the end of today, in the meantime you can downgrade to `0.1.39` which won't fail

**Comment by OpTicFlutter** [comment]
> it will be fixed by the end of today, in the meantime you can downgrade to `0.1.39` which won't fail

Okie ^^
