### ISSUE TITLE
[bug fix] launcher does not work offline

### ISSUE THREAD

**Issue by Zedb0T** [open-goal/launcher#32]
Can easily just say an internet connection is required during initial setup.

But maybe it would be possible to bundle the installer with a "baseline" release so the launcher could at least setup something offline, even if it isn't the latest version.

**Comment by xTVaser** [comment]
It is possible, but it will heavily balloon the size of the installer for a very small minority of users https://tauri.app/v1/guides/building/windows#offline-installer this is only needed for people that havn't installed their latest Windows updates.

The launcher comes with the jak-project release -- it does not download it during installation
