### ISSUE TITLE
[Feature] Track and display time played in launcher

### ISSUE THREAD

**Issue by NeoFoxxo** [open-goal/launcher#320]
I would love if playtime tracking could be added to the launcher and be displayed on the front page like other launchers. I did actually try to figure this out myself but since I have no rust experience I could just find where the launcher started the game but nowhere to track when the game closed lol.  Maybe this was already planned since I saw a comment in the code mentioning this feature. Anyway I feel like this could be a great feature for the launcher.

**Comment by Zedb0T** [comment]
Id really like to see a global stats thing for the entire game, number of deaths number of cells blue eco collected lurker puppies killed time spent playing etc.

Number of orbs

**Comment by NeoFoxxo** [comment]
Yeah that would be cool but it would involve somehow interacting with the game, where tracking playtime theoretically should be simple. But i guess you probably already have an idea on how to get those specific game stats lol

**Comment by xTVaser** [comment]
Yeah this is something I've wanted to add, there's TODOs in the code for it but no issue for it yet.  The game is launched as a separate process (so the launcher does not have to be open for the game to continue working)  so nothing really tracks when the game is closed right now.

Tracking things like game stats is more tricky -- it would require parsing more of the game's save files and persisting that info (ie. if someone dies 10 times on slot 1, then makes a new game on slot 1 and dies another 10 times -- you'd expect 20 deaths total).  Parsing the save files is something I started doing to enable the background changing based on your game completion - https://github.com/open-goal/launcher/blob/3e351136bc7234cc6466872231bda51195e2927c/src-tauri/src/commands/game.rs#L163-L176

**Comment by NeoFoxxo** [comment]
I could create an external process that checks if the game process is running and then have it send the time it has been running to a json file that gets read by the launcher. That process could then be started the same time the launcher starts the game.

**Comment by xTVaser** [comment]
There's likely a way to monitor the `gk` process via rust in the launcher itself, involving an external process might just add more instability / then we have to worry about running more external binaries.

This is a little hand-wavy as I'm also new to rust but it seems reasonable to: in a separate thread, [wait](https://doc.rust-lang.org/std/process/struct.Child.html#method.wait) for the [spawned process](https://github.com/open-goal/launcher/blob/3e351136bc7234cc6466872231bda51195e2927c/src-tauri/src/commands/binaries.rs#L725) to exit.  Then persist the data to the config.

I think it's reasonable that if you close the launcher that tracks your time-played, to end up not having your time played tracked.  No different than Steam.

**Comment by Zedb0T** [comment]
Yeah I even want to see like meters ran etc, but that stuff isnt really possible without being invasive to the game in some nature

**Comment by NeoFoxxo** [comment]
Alright I have got the functionality complete in this commit: 0ce3bb8f62ee94eee02024603684d8847eabc108.

To track the playtime I start a timer before the game is launched and wait for the game to exit. Once it has exited I store the seconds the game was active to a `playtime.txt` file. If there already was seconds in the file they will be added together. This file is then read in the front end and the seconds are formatted and displayed on the game page.

<img src="https://github.com/open-goal/launcher/assets/104744179/7e0fa41d-fa80-450e-943f-3ca7f712f732" width="70%">

Two things to note though are currently:

- Waiting for the game to exit blocks some threads in the application causing some pages to infinitely load if the game is running and the versions page for example is accessed. I did try running it in a separate thread but it did not work, maybe someone with actual rust knowledge could help out with this. Though this may not be an issue since these settings are not normally modified when the game is running. 
- The playtime is currently stored in seconds in a txt file in the config directory (`AppData\Roaming\OpenGOAL-Launcher` on Windows). I think the playtime should rather be stored in the `settings.json` file under the respective game. But adding playtime to the `settings.json` looks pretty complicated with serde_json.

If these issues are fine I'll submit a PR

**Comment by xTVaser** [comment]
Nice! your changes will need a bit of work (every instance of `.unwrap()` is a potential spot for an unhandled runtime error for example), but having something working is a great place to start.

> But adding playtime to the settings.json looks pretty complicated with serde_json.

It's not too bad, when you open a PR I can probably give some feedback on how you'd do it.

And yeah hopefully we can figure out the threading because the backend being blocked while the game is opened will definitely be something someone will complain about -- someone wanting to launch two instances of a game for example.  Or launch the REPL while the game is running (an actual useful situation)

**Comment by NeoFoxxo** [comment]
Hey @xTVaser could you please check out the PR?

**Comment by xTVaser** [comment]
yeah ill try my best to give it a look in the coming weeks, this month is a bit busy.

**Comment by trippjoe** [comment]
> Yeah I even want to see like meters ran etc, but that stuff isnt really possible without being invasive to the game in some nature

it would be cool to have a stats page for stuff like this.
