### ISSUE TITLE
Automatically set version on download

### ISSUE THREAD

**Issue by Zedb0T** [open-goal/launcher#346]
If a version is downloaded, and its the first/only version the user has installed then automatically select it as active and save the change.

Currently after downloading they need to click the sphere to select it then save the change

**Comment by Zedb0T** [comment]
Maybe just skip the whole VCS at first, and just default them to the latest version, and update it when a release is cut tbh. Keep the menu and let people play/see older versions if they want but by default we should probably just give them the latest version + keep it updated without input/confusion.

(I keep seeing people on 2-3 month old jak 1 builds with ugly final boss red rings)

**Comment by xTVaser** [comment]
I like the idea of automatically saving the version change if they have no version currently selected, but I don't like skipping it completely.  I think it's important to force the user to learn how to download and select a version so they can keep it updated/downgrade it -- I really don't believe the current UX is that confusing to the majority of people that it constitutes a change.

- Having a link with a bold red color of UPDATE AVAILABLE at the top is pretty obvious that an update is available
- And then clicking that link makes them perform the exact same steps they did when they first installed the game.

The tutorial video should clear up confusion for the 1% of remaining users that struggle with not knowing what to click.

**Comment by Milkfat32** [comment]
Perhaps the table should have a header on the radio button column so people know that it is an option that exists? It can be easy to miss. Like Version, Date and Changes? And adding one for the download/trash (Action maybe?)

And maybe if no selection has been made it should warn the user if they try to leave the page without a selection? So they have to actively make the decision to select a version?
