### ISSUE TITLE
Missing libthai in appimage

### ISSUE THREAD

**Issue by Melechtna** [open-goal/launcher#368]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/launcher/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game
- [X] If possible, I've attached the support package zip file to the issue [see how here](https://github.com/open-goal/launcher#asking-for-help)

### Attach Support Package / Log Files (drag and drop)

Cannot start launcher

### Describe the Bug

The appimage is missing libthai.so.0

### How To Reproduce

Run the launcher in NixOS

### Operating System

NixOS unstable

### Launcher Version

2.3.1

### Tooling Version

Can't start launcher

**Comment by xTVaser** [comment]
This is a known upstream issue, apparently with AppImages in geneeral.  it's out of our hands 
https://github.com/tauri-apps/tauri/issues/4930
https://github.com/AppImageCommunity/pkg2appimage/issues/538
