### ISSUE TITLE
"Copy executable path" option does not enclose project path in quotes

### ISSUE THREAD

**Issue by ManDude** [open-goal/launcher#382]
`C:\Users\Hazzy\Documents\Jak Games\versions\official\v0.2.2\gk.exe -v --proj-path C:\Users\Hazzy\Documents\Jak Games\active\jak1\data --game jak1 -- -boot -fakeiso` is an invalid set of launch parameters

**Comment by HazzyDevil** [comment]
Quickly chiming in here. In addition to handling the enclosing of the paths correctly, assuming we are wanting users to be able to run this command from powershell, then the command the gets copied to our clipboard should be `& "C:\Users\Hazzy\Documents\Jak Games\versions\official\v0.2.2\gk.exe" -v --proj-path "C:\Users\Hazzy\Documents\Jak Games\active\jak1\data" --game jak1 -- -boot -fakeiso` using the example above. This will make running the game a simple copy/paste into powershell without any further work like changing directory to gk.exe and running it as that is handled by the ampersand in the command above.

Alternatively, if users are meant to run it from cmd, then the command would be `"C:\Users\Hazzy\Documents\Jak Games\versions\official\v0.2.2\gk.exe" -v --proj-path "C:\Users\Hazzy\Documents\Jak Games\active\jak1\data" --game jak1 -- -boot -fakeiso` as ampersand wont work here, but unfortunately this command wont work in powershell either. So probably should make it clear where the command needs to go (or an option to get either a command for powershell or cmd could work too).

Lastly, I know this isn't an issue with other applications, but gk.exe doesn't appear to like enclosing paths using single quotes ( ' ) and will error out. I figure it's worth mentioning as enclosing paths in either single or double quotes shouldn't really matter.

`.\gk.exe -v --proj-path "C:\Users\Hazzy\Documents\Jak Games\active\jak1\data" --game jak1 -- -boot -fakeiso` will work fine (double quotes example), but `.\gk.exe -v --proj-path 'C:\Users\Hazzy\Documents\Jak Games\active\jak1\data' --game jak1 -- -boot -fakeiso` doesn't work (single quote example).

**Comment by xTVaser** [comment]
Duplicate of https://github.com/open-goal/launcher/issues/367
