### ISSUE TITLE
Missing: Lithuanian language for the Launcher

### ISSUE THREAD

**Issue by Zorklis** [open-goal/launcher#399]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/launcher/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game
- [X] If possible, I've attached the support package zip file to the issue [see how here](https://github.com/open-goal/launcher#asking-for-help)

### Describe the Bug

On November 2023, I have 100% translated the Launcher to Lithuanian. (Currently 1 out of 7 to be 100%) -  :)
The issue is that it's not present in the "Change Locale" tab among the other dozens of languages.

### How To Reproduce

Check the locales.
![OpenGOAL-Launcher_nJJLiHlUo7](https://github.com/open-goal/launcher/assets/85455465/237c717b-3237-4191-b22c-9f97535256bb)

### Operating System

Windows 10

### Launcher Version

v2.4.0

### Tooling Version

not set!

**Comment by trippjoe** [comment]
This is not a bug, your translations are **awaiting approval**. [Your translations](https://crowdin.com/project/opengoal-launcher/activity-stream?lang=29) were submitted between November 4th and November 6th. The [latest launcher version](https://github.com/open-goal/launcher/releases/tag/v2.4.0) was released on November 6th. Even if they were approved after November 6th, it would require a new release for them to show up.

**Comment by xTVaser** [comment]
This is indeed not a bug, but let's keep it open to track the missing piece of work that has to be done.

**Comment by xTVaser** [comment]
Added in https://github.com/open-goal/launcher/pull/429
