### ISSUE TITLE
distributing: AppImage is a blank screen

### ISSUE THREAD

**Issue by xTVaser** [open-goal/launcher#41]

**Comment by xTVaser** [comment]
https://discord.com/channels/616186924390023171/731495064508825731/968988490769526794 This problem is due to `libgstreamer` not being included for whatever reason.

Following the steps there to manually include it solves the problem

**Comment by xTVaser** [comment]
Related - https://github.com/tauri-apps/tauri/issues/4092

**Comment by xTVaser** [comment]
Fixed from upstream tauri fix, but https://github.com/open-goal/launcher/issues/42 remains

**Comment by verbes4** [comment]
im also getting this error
