### ISSUE TITLE
Launcher Only Displays White Screen in Steam Deck Game Mode Only

### ISSUE THREAD

**Issue by jacobranson** [open-goal/launcher#419]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/launcher/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game
- [X] If possible, I've attached the support package zip file to the issue [see how here](https://github.com/open-goal/launcher#asking-for-help)

### Describe the Bug

On the Steam Deck, in Game Mode, the launcher cannot render anything. It is a big white box. In desktop mode on the Steam Deck, this issue does not occur. Using the latest launcher version via AppImage. I have tried the last 3 major launcher versions, and have gotten the same result.

### How To Reproduce

Perform all the following steps on a Steam Deck:

- Download the latest launcher AppImage file from GitHub Releases.
- Extract the folder.
- Make the launcher executable.
- Add it to Steam as a Non-Steam game.
- Launch the game in Game Mode.

### Operating System

SteamOS 3.5.7

### Launcher Version

v2.4.0

### Tooling Version

N/A

**Comment by xTVaser** [comment]
This is known, the launcher has never been intended to work well on the steamdeck.  I welcome contributions that would fix it but the decky plugin was created to provide a more native experience.

See https://github.com/open-goal/launcher/issues/60 and https://github.com/open-goal/decky-plugin
