### ISSUE TITLE
tooling does not install

### ISSUE THREAD

**Issue by Raucki** [open-goal/launcher#432]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/launcher/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game
- [X] If possible, I've attached the support package zip file to the issue [see how here](https://github.com/open-goal/launcher#asking-for-help)

### Describe the Bug

won't let you select a tool

### How To Reproduce

![Nimetön](https://github.com/open-goal/launcher/assets/156436580/cee7948a-61fb-4cce-ab1e-7f05048ce639)

### Operating System

win 11

### Launcher Version

v2.4.1

### Tooling Version

v0.2.7

**Comment by xTVaser** [comment]
Please attach the support package which hopefully has logs for why it failed.

Also this seems to highlight another bug related to recent changes -- the tooling version changed despite not being able to be downloaded.

**Comment by xTVaser** [comment]
Could not replicate, open if you have reproduction steps.
