### ISSUE TITLE
MSVCP140.dll, VCRUNTIME140.dll, VCRUNTIME140_1.dll were not found.

### ISSUE THREAD

**Issue by yodaxtah** [open-goal/launcher#436]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/launcher/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game
- [X] If possible, I've attached the support package zip file to the issue [see how here](https://github.com/open-goal/launcher#asking-for-help)

### Attach Support Package / Log Files (drag and drop)

I made the screenshots on another account with an empty folder, but I'm writing this bug report on my own account :( Thus I have two different support packages. I honestly don't think it matters, but just in case. The first has already compiled and completed games, the second was empty.

- [opengoal-support-package.zip for OpenGoalSelfSetDirectory (original)](https://github.com/open-goal/launcher/files/14220741/opengoal-support-package.zip)
- [opengoal-support-package.zip for OpenGoal2 (empty)](https://github.com/open-goal/launcher/files/14220909/opengoal-support-package.zip)

### Describe the Bug

<details>

<summary>

When I launch the launcher (exe) for the first time, I get the following behavior. The version is not detected. I download the latest tooling, and OpenGL's version seems not detectable. I downloaded the latest NVIDIA driver, but it had no effect.

</summary>

![1](https://github.com/open-goal/launcher/assets/159531413/21e306c5-743b-4029-b26c-4796215fb620)
![2](https://github.com/open-goal/launcher/assets/159531413/6c26f6e9-c5ac-497a-bd30-21ad3c31142c)

</details>

<details>

<summary>

Not important probably, but sometimes I also get this screenshot instead to be the first. (Notice the error message in the top right corner that wasn't there on Admin account.

</summary>

![1b](https://github.com/open-goal/launcher/assets/159531413/2208498f-4f7c-4c77-bb9a-941892f63500)

</details>

<details>

<summary>

I then closed and reopened the launcher and a bunch op pop-ups started to appear. After clicking through, a link is visible that redirects me to a site where I could find my OpenGL version. According to Task manager, I have an [NVIDIA MX 250](https://www.techpowerup.com/gpu-specs/geforce-mx250.c3353), which lists OpenGL 4.6.

</summary>

![3](https://github.com/open-goal/launcher/assets/159531413/193b743a-8adf-4c9b-9d57-6610c3c8cff4)
![4](https://github.com/open-goal/launcher/assets/159531413/2aa9de1d-73e8-4602-a856-2168124adc18)
![5](https://github.com/open-goal/launcher/assets/159531413/a62e3cfb-c5d4-4f19-83da-92069c81509f)
![6](https://github.com/open-goal/launcher/assets/159531413/7d1ca203-a71c-4959-83dc-e4bcba2deea6)

</details>

<details>

<summary>

Two more clicks, and I ended up at the same error message as the first time I launched the launcher. I believe I missed on screenshot, so there was actually a dialog between the two next screenshots.

</summary>

![7](https://github.com/open-goal/launcher/assets/159531413/5886c95d-55e7-4f95-8b4f-425ce6af32f9)
![9](https://github.com/open-goal/launcher/assets/159531413/3431bae3-8108-42a7-96f8-36dd9edb9742)

</details>

---

Issues I searched for
- [dll](https://github.com/open-goal/launcher/issues?q=dll)
- [was not found](https://github.com/open-goal/launcher/issues?q=was+not+found)
- [Unable to detect if your system supports OpenGL](https://github.com/open-goal/launcher/issues?q=Unable+to+verify+if+your+GPU+supports+OpenGL)
- [system does not meet all the minimum requirements](https://github.com/open-goal/launcher/issues?q=system+does+not+meet+all+the+minimum+requirements)

### How To Reproduce

Hm, I'm not sure about the relevancy, but I'll describe in more detail what I did. I don't expect anyone to do this, but it may be useful to have a better idea if you're willing to help with this issue. (Feel free to skip otherwise.)

1. I tried compiling the reverse engineered project of GTA III ([re3](https://github.com/halpz/re3)), but failed due to missing OpenAL.dll, libmpeg123-0.dll and another common dll which I can't remember. (The internet told me that missing dlls are usually a sign of a corrupt Windows (virus). Since I had been planning to reinstall, I decided to do so, in the hopes that the compilation would work. Giving it a second thought, it could be that the game is simply looking for an older version of a dll, since the game itself is very old, _but I'm just guessing_.)
2. Either way, I have a dual boot, so I decided to go with the [windows creation tool](https://www.microsoft.com/en-us/software-download/windows10) ([second button](https://go.microsoft.com/fwlink/?LinkId=691209)). I choose in the dialog to keep my files and remove all my applications. I let the tool run two days ago.
3. I downloaded the OpenGOAL exe from the website and gave it the same folder as before the "reinstallation" (or whatever it is exactly), and now it starts throwing errros.
4. After Windows had automatically updated some drivers, I tried once more, without success.
5. I uninstalled the launcher with the tool and installed it again. This time I took a new folder. From here on, the error messages are described already.

A few notes
- Now, I did have Visual Studio 2019 Enterprise installed before, and now it's gone too, but I don't expect that every user has that installed. I just find it particular that I'm supposed to manually install these dlls. Strangely enough, in this case the internet does tell me to install them <sup>[[1]](https://answers.microsoft.com/en-us/windows/forum/all/vcruntime140dll-was-not-found/f43d5afd-9239-4913-8f32-20e44a959e13),[[2]](https://answers.microsoft.com/en-us/windows/forum/all/vcruntime140dll-and-msvcp140dll-missing-in-windows/220f1caf-8eb9-413d-a7fe-1b13df1bfa5d),[[3]](https://helpdeskgeek.com/windows-10/how-to-fix-a-vcruntime140-dll-is-missing-error-on-windows-10/),[[4]](https://www.freecodecamp.org/news/vcruntime140-dll-was-not-found-solved-on-windows-10-pc/)</sup>, instead of "it's a virus!". Did all users once do that? Or will the launcher not work on the newest fresh version of Windows 10? (Or is mine simply broken?)
- I did install the Visual Studio 2022 Community edition before installing the OpenGOAL exe.
- **_I did play after the latest update of the launcher, and everything worked perfectly. (In fact, I compiled and completed the first two games without any trouble.) I'm reasonably sure that the issue is the direct cause of the re-installation of Windows._**
- I did a full system scan from settings, and an additional full system scan with Microsoft's [Malicious Software Removal Tool](https://support.microsoft.com/en-us/topic/remove-specific-prevalent-malware-with-windows-malicious-software-removal-tool-kb890830-ba51b71f-39cd-cdec-73eb-61979b0661e0) --- it took 6h!! --- and found 0 problems _before the Windows re-installation_. Regarding the "there may be a virus on my system", I'm not sure what to think. OpenGOAL is one of the few programs I reinstalled/ran, along common ones like Firefox, so I'd find it unlikely to already be contaminated again, if the "Windows reinstallation" was effective at removing the possibly existing virus.

Solutions I haven't tried yet
- I could manually install the dlls, but I'm creating the issue anyway, in case it's not my PC. It could be just my PC, but even then, the missing dlls may be just a symptom, not the cause (of a very well hidden virus maybe for example, I don't know).
- I could bypass the requirements, but I'm not sure about the consequences.

### Operating System

Windows 10

(details copied from Settings About):

**Edition**	Windows 10 Home
**Version**	22H2
**Installed on**	‎2/‎7/‎2024
**OS build**	19045.3803
**Experience**	Windows Feature Experience Pack 1000.19053.1000.0

### Launcher Version

v2.4.1

### Tooling Version

v0.2.7

**Comment by yodaxtah** [comment]
I'm not sure but maybe issue #303 is related. I came across "VC++" often at websites proposing fixes when searching for the cause of the missing dlls.

If this is the case and I understood correctly --- that is, the libraries are not installed by the installer but required by the game --- then I'll comfortable close this issue and download the dlls from the internet in meanwhile (instead of waiting for a fix).

Just because I have some C++ background and I'm confused with the issue description: it mentions that Tauri statically links a library, and I always thought it means the library is included, making the exe bigger and faster<sup>[[1]](https://stackoverflow.com/questions/4667882/is-a-statically-linked-executable-faster-than-a-dynamically-linked-executable)</sup>, and thus that's what I'd need. But this is the current situation already, yet I'm dependent of a dynamically linked library. (??) Maybe I'm missing the point; I have no idea about the workings of Tauri at all.

**Comment by Hat-Kid** [comment]
The issue you are facing is not related to the launcher, it's the game (`gk.exe`) that requires these libraries. When the launcher checks for system requirements, it runs the game's executable in a limited mode to check your GPU's OpenGL version, which is where this error is coming from. You should be able to get them by installing the Microsoft Visual C++ Redistributables.

**Comment by ManDude** [comment]
You need to install the x64 Microsoft Visual C++ 2015 Redistributables.

*Never* directly download DLLs off the internet.

**Comment by yodaxtah** [comment]
Hi, thanks a lot for the quick replies! I have a few questions, because I'd like to understand _why_ they are missing.

> You should be able to get them by installing the Microsoft Visual C++ Redistributables.

- Why didn't I have to do that the first time (in June)? Is that because I coincidentally downloaded them through Visual Studio maybe long before the first installation? Or did a game once download that for me?
- And is it expected that these libraries are missing on a fresh install of Windows? Or did I miss instructions on dependencies that should be installed somewhere? 

I did (only now) see that [dependencies are described on the jak-project](https://github.com/open-goal/jak-project/blob/master/README.md#windows), but those are intended for developers. I expected that if I followed the non-developer installation, it'd be taken care of for me to prevent people with no knowledge from starting to install dlls from the internet for example :-)

I just wonder if other people had to manually install the Microsoft Visual C++ Redistributables as well, and if not, why. I quickly looked for issues relating to dlls in the jak-project, but quickly skimming the titles ([dll](https://github.com/open-goal/jak-project/issues?q=dll), [msvcp](https://github.com/open-goal/jak-project/issues?q=msvcp), [system supports OpenGL](https://github.com/open-goal/jak-project/issues?q=system+supports+OpenGL+)), they don't seem to be related or have no results. Maybe I'm still looking in the wrong repository? :p

> Never directly download DLLs off the internet.

I agree, from what I read, that's opening the door to mallware. [Microsoft does however host the dlls (or instructions) on their website](https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version), but I'll look into proper ways of installing it (through VS if possible) once I get back to my computer.

**Comment by Hat-Kid** [comment]
Windows does not come with these libraries installed by default, however, a lot of games and other programs require them, so chances are most people already got them that way before trying to run OpenGOAL (and it's mentioned on our website in the [requirements section for Windows](https://opengoal.dev/docs/usage/installation/#windows-specific)).

Since you said you wiped all applications from your install, you removed those libraries as well.

**Comment by yodaxtah** [comment]
Ahh, there it is.

I will add a "how I installed it and get it working" in case someone else encounters this issue, but will close the issue for now, assuming I will manage to do that :))

Thanks a lot!! :)

**Comment by yodaxtah** [comment]
Well, it was as simple as following the link above to the [requirements for Windows](https://opengoal.dev/docs/usage/installation/#windows-specific) and clicking the following link. (Go to the open goal page itself, in case it got updated!)

> You may need to install the [latest 64-bit C++ redistribution](https://aka.ms/vs/17/release/vc_redist.x64.exe).

It will download a Visual C++ 2015-2022 installer. This download link is the exact same as the one that can be found on the [Microsoft page I referred to previously](https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version). I managed to compile the first game again🥳

**Comment by yodaxtah** [comment]
As I mentioned in the issue about controllers, I've lost the saves. The Windows creation tool will remove the hidden `AppData` folder, in which one's saves and other settings are stored. After the applications had been removed, a huge `Windows.old` folder will be created. It's a backup/copy of the `Windows` folder at the same directory before the tool's execution -- at least, that's what I thought -- but fortunately, this happens to contain the `Users` directory as well, where one can find the saves. Those of `jak1` for example are in `Windows.old/Users/username/AppData/OpenGoal/jak1/saves/BASCUS-12345ABCDEFG!`. Replacing `jak1`'s current saves folder of a similar name with this folder will restore the original saves.

I have my saves back!! :D 🎉
