### ISSUE TITLE
Not working on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by vandersdg** [open-goal/launcher#462]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/launcher/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game
- [X] If possible, I've attached the support package zip file to the issue [see how here](https://github.com/open-goal/launcher#asking-for-help)

### Attach Support Package / Log Files (drag and drop)

[36m[22:55:30][opengoal_launcher][[36mINFO[0m[36m] Logging Initialized[0m
[36m[22:55:30][opengoal_launcher][[36mINFO[0m[36m] /home/user/.config/OpenGOAL-Launcher/logs/app/2024-04-03.log[0m
[36m[22:55:30][opengoal_launcher::config][[36mINFO[0m[36m] Loading configuration at path: /home/user/.config/OpenGOAL-Launcher/settings.json[0m
[31m[22:55:30][opengoal_launcher::config][[31mERROR[0m[31m] Could not locate settings file, using defaults[0m
[36m[22:55:30][opengoal_launcher][[36mINFO[0m[36m] application starting up[0m
[36m[23:05:57][opengoal_launcher][[36mINFO[0m[36m] Logging Initialized[0m
[36m[23:05:57][opengoal_launcher][[36mINFO[0m[36m] /home/user/.config/OpenGOAL-Launcher/logs/app/2024-04-03.log[0m
[36m[23:05:57][opengoal_launcher::config][[36mINFO[0m[36m] Loading configuration at path: /home/user/.config/OpenGOAL-Launcher/settings.json[0m
[31m[23:05:57][opengoal_launcher::config][[31mERROR[0m[31m] Could not locate settings file, using defaults[0m
[36m[23:05:57][opengoal_launcher][[36mINFO[0m[36m] application starting up[0m
[36m[23:06:04][opengoal_launcher][[36mINFO[0m[36m] Exit requested, exiting![0m

### Describe the Bug

When I start it, I get stuck in a window saying to select locale, but the window can't be clicked, so I cannot select any locale and it just stays there forever.

![Captura de tela de 2024-04-03 23-12-06](https://github.com/open-goal/launcher/assets/90361836/9470112d-647f-462e-b232-dee2aa74a0d3)

### How To Reproduce

1. Use linux
2. Execute the appimage
3. Get stuck on select locale window and there is no way to even click on it

### Operating System

openSUSE Tumbleweed

### Launcher Version

from 2.3.1 to 2.4.3 (yes I tested it all)

### Tooling Version

I can't launch it so idk

**Comment by dallmeyer** [comment]
https://github.com/rstudio/rstudio/issues/10037

^ user has this same error with other software while using openSUSE Tumbleweed
> atk-bridge: get_device_events_reply: unknown signature

wonder if this might be an OS-specific issue

**Comment by dallmeyer** [comment]
https://gitlab.com/Remmina/Remmina/-/issues/2903

similar story here - different software, same OS, same error

**Comment by vandersdg** [comment]
@dallmeyer Thank you for your insights! Today, I launched YaST and downloaded the KVM virtualization and KVM tools, and suddenly it is working perfectly. I'm not sure if it is related, but it is now fixed, and this was the only change I made. My computer wasn't even rebooted. (Just reporting lol)

**Comment by xTVaser** [comment]
So, tauri renders the window via `webkit2gtk`.  The warnings in the logs may be indicative of a problem, or just be complete red-herrings.

So on one hand that may explain why things suddenly started working, perhaps yast updated this dependency (or some other less important one) and things are working.  However that would be confusing, as that's the entire point of an AppImage -- so that your system dependencies dont matter.

So yeah, really strange but if it's suddenly working that lowers the urgency -- one day I'll make a opensuse VM and see if i can reproduce.

**Comment by xTVaser** [comment]
I'm going to assume this is fine, and if not, will be fine with the upcoming update to Tauri V2 / switch to better flatpaks.  I tried to setup a openSUSE tumbleweed VM to confirm/debug and it couldn't even install the OS without kernel panic'ing over mounting the fs :(
