### ISSUE TITLE
support compressed disc's in the form of .chd

### ISSUE THREAD

**Issue by CuddleBear92** [open-goal/launcher#465]
Support .chd support! 
Compressed disc support in the form of chd.
This way people can keep the most storage effective format (i believe) while it might also be used by emulators that already support the format. In all 3 Jak games, you can compress it to about half the size compared to the normal iso.
This also makes sense for mobile systems like a SteamDeck or a Laptop where storage is scarce and also speed up file reading over the network.

https://github.com/charlesthobe/chdman
https://github.com/umageddon/namDHC

![image](https://github.com/open-goal/launcher/assets/8496821/a48401bd-207c-4a97-9d83-75e3b3de2da1)

**Comment by xTVaser** [comment]
This would need to be a change made in the main `jak-project` project, not here.

However I'm not convinced it would actually be a good one.  Emulators are a different scenario, the ISOs are the only input for playing the game.

For OpenGOAL, the ISO is just the easiest way for the user to provide the files for the tools to use.  The ISO is fully extracted to disc, eliminating any benefits of better compression.  Not the mention the fact that CHD would be another dependency we'd have to integrate with -- but with no real tangible benefit.

The only benefit i can see is for users that have fully converted their libraries from ISO to CHD to save space.  However in this case, there are tools to convert back temporarily -- as well as the launcher will soon support installing from a folder, and tools like 7zip can be used to extract a CHD file.
