### ISSUE TITLE
jak-project tool not working on a linux CPT

### ISSUE THREAD

**Issue by Mimar999** [open-goal/launcher#477]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak1+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

" Tooling appears to be missing critical files. This may be caused by antivirus software. You will need to redownload the version and try again."

Hey, i have installed opengoal on linux, then could not access to the official list of versions for tooling through the launcher, so i downloaded the 0.2.10 jak-project for the tooling

Then select the iso, but unfortunately i get the error i wrote just before

I don't know if the error comes from the version itself not being the right one, or the computer (that is a university computer so it might block something somehow)

Can someone help me ? 

P.S. 
It doesnt even allow me to try to install Jak 2 by the way and select any iso, i can only do it for Jak 1 and then i get the error message at the extraction

### How To Reproduce

Installing the launcher on linux and using unoff version

### Does this problem occur on original hardware or PCSX2?

Didn't check

### Expected Behavior

Should install normally

### Environment Information

Ubuntu 20.04.6 LTS

Version of the launcher : 2.4.3

Version of the tooling : jak-project 0.2.10 (i tried with another one 0.2.9, didnt work either, same error)

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by dallmeyer** [comment]
Did you check your antivirus software to see if it quarantined the game binaries? You'd be looking for extractor / goalc / gk

It also wouldn't surprise me if your university has installations locked down in some way

**Comment by xTVaser** [comment]
> Hey, i have installed opengoal on linux, then could not access to the official list of versions for tooling through the launcher, so i downloaded the 0.2.10 jak-project for the tooling

You most likely extracted the tooling incorrectly so it does not have access to the required binaries, or as mentioned in the error and the above comment, the file was quarantined or prevented from being executed by an anti-virus.

A properly extracted version should look like the following in your installation directory.
![image](https://github.com/open-goal/launcher/assets/13153231/c79b0196-a590-408c-b421-d99a57fbbee5)
