### ISSUE TITLE
Official toolling versions not loading

### ISSUE THREAD

**Issue by jojoharry16** [open-goal/launcher#490]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/launcher/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game
- [X] If possible, I've attached the support package zip file to the issue [see how here](https://github.com/open-goal/launcher#asking-for-help)

### Attach Support Package / Log Files (drag and drop)

[opengoal-support-package.zip](https://github.com/open-goal/launcher/files/15389379/opengoal-support-package.zip)

### Describe the Bug

The official tooling version section on the settings page is stuck on the loading screen. Logs don't give any useful information, just saying I'm up to date, which it also checks on startup

[32m[13:49:55][reqwest::connect][[32mDEBUG[0m[32m] starting new connection: https://raw.githubusercontent.com/[0m
[32m[13:49:55][hyper::client::connect::dns][[32mDEBUG[0m[32m] resolving host="raw.githubusercontent.com"[0m
[32m[13:49:55][hyper::client::connect::http][[32mDEBUG[0m[32m] connecting to 185.199.109.133:443[0m
[32m[13:49:55][hyper::client::connect::http][[32mDEBUG[0m[32m] connected to 185.199.109.133:443[0m
[32m[13:49:55][hyper::proto::h1::io][[32mDEBUG[0m[32m] flushed 130 bytes[0m
[32m[13:49:55][hyper::proto::h1::io][[32mDEBUG[0m[32m] parsed 24 headers[0m
[32m[13:49:55][hyper::proto::h1::conn][[32mDEBUG[0m[32m] incoming body is content-length (4434 bytes)[0m
[32m[13:49:55][hyper::proto::h1::conn][[32mDEBUG[0m[32m] incoming body completed[0m
[36m[13:49:55][opengoal_launcher::commands::logging][[36mINFO[0m[36m] Launcher is up to date - {"shouldUpdate":false}[0m

### How To Reproduce

Open OpenGOAL launcher, see "No Tooling Version Configured" warning, click button to set version, watch intently as nothing happens.

### Operating System

Windows 11 Pro version 10.0.22631 Build 22631

### Launcher Version

2.4.4

### Tooling Version

not set!

**Comment by jojoharry16** [comment]
I should mention I have a background in software development, but not in reverse engineering. If I can do anything to assist in troubleshooting, or in this project in general, I would be delighted to assist :)

**Comment by xTVaser** [comment]
This is odd, and i don't see any obvious error, but this is a missing spot in the code (gracefully handling not being able to get the versions).

All that page does is hit this URL https://api.github.com/repos/open-goal/jak-project/releases?per_page=100 and render the results, are you able to open that link in a normal browser successfully at the same time that the launcher fails to do so?

**Comment by jojoharry16** [comment]
Ugh, figured out the issue... I have an app called SimpleWall that blocks internet access to all app unless allowed through. Somehow this request got blocked even though the OpenGOAL launcher is allowed through

**Comment by pipman3000-rettata** [comment]
To be more specific, it was msedgewebview2 that needed to be allowed through, at least in my case.

**Comment by xTVaser** [comment]
WebView2 is used to render the application in general (on windows).  It's not the root cause of this persons problem (where outbound network requests were blocked).

**Comment by pipman3000-rettata** [comment]
"Somehow this request got blocked even though the OpenGOAL launcher is allowed through"
This was the root of their problem.  I was experiencing the same thing using a similar application for a firewall.  For some reason, despite allowing the launcher through the firewall, requests for the tooling versions as well as the cover images for mods were being blocked by the firewall.

Disabling the entire firewall does get around that temporarily, but it's not a real solution.  What I specified allows me and any others (including the original poster) to continue using our firewall solution while also allowing tooling versions to load properly (via msedgewebview2)

**Comment by xTVaser** [comment]
Ah sorry I misunderstood your reply, your issue is you needed to allow msedgewebview2 in your firewall, not that you just were missing webview2.  Makes sense
