### ISSUE TITLE
White screen launcher Steam Deck gaming mode

### ISSUE THREAD

**Issue by Kfollen93** [open-goal/launcher#525]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/launcher/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game
- [X] If possible, I've attached the support package zip file to the issue [see how here](https://github.com/open-goal/launcher#asking-for-help)

### Describe the Bug

When adding the open goal launcher 2.4.9 AppImage to Steam Deck as a non-Steam game, and launching it in gaming mode it is a white screen (although the buttons still work if you remember where they are and can blindly click on them). The launcher is viewed properly in Desktop mode.

Is there a way to simply add the executables (Jak 1 and 2) to Steam to circumvent the launcher?

### How To Reproduce

Add the open goal launcher 2.4.9 AppImage to Steam Deck as a non-Steam game, and launching it in gaming mode.

### Operating System

Linux (Steam Deck)

### Launcher Version

2.4.9

### Tooling Version

0.2.14

**Comment by Kfollen93** [comment]
You can in fact add the games directly as a non-Steam game and skip the launcher!

While in desktop mode:
There is an option to copy the game's executable path on the bottom right cog wheel of the launcher. It is very hard to click when using the Steam Deck's trackpad, as it moves and it also doesn't seem to recognize every click. However, once you are able to click it (be patient, you'll get it), you can then add the launcher as a non-Steam game, and then update the paths in properties to be the path you copied. This will work for both Jak 1 and Jak 2, and you will not need the launcher anymore.

I am leaving the issue open, as it is still bugged if a user wanted to add the launcher itself to boot the games via gaming mode.

**Comment by xTVaser** [comment]
The launcher at this time is not intended for use on the steam deck, see https://opengoal.dev/docs/usage/installation/#linux-steam-deck for recommended installation steps.

Related issues:
- https://github.com/open-goal/launcher/issues/419
- https://github.com/open-goal/launcher/issues/60
