### ISSUE TITLE
Move requirement checks out of the progress bar flow

### ISSUE THREAD

**Issue by xTVaser** [open-goal/launcher#57]
This can be confusing as the progress bar implies something is going on 
![image](https://user-images.githubusercontent.com/13153231/174202017-7d07b3ab-3675-4620-abfb-9c1c10182575.png)

Better to maybe just show a check list of requirements -- what they have and what they don't and only show the progress-bar once the setup has begun (or disable the setup button if you dont meet said requirements, maybe that's already done though!)

**Comment by trippjoe** [comment]
- [ ] Add button for compatibility check to settings menu
- [ ] Auto run compatibility check on first launch of app, save to user config file
- [ ] On app open pull compatibility Boolean from config
