### ISSUE TITLE
Tooling versions page no longer loads

### ISSUE THREAD

**Issue by hypevhs** [open-goal/launcher#586]
### Acknowledgements

- [x] I have [searched](https://github.com/open-goal/launcher/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [x] I understand that I am supposed to provide my own legitimately obtained copy of the game
- [x] If possible, I've attached the support package zip file to the issue [see how here](https://github.com/open-goal/launcher#asking-for-help)

### Attach Support Package / Log Files (drag and drop)

I cannot download the support package due to another bug involving wgpu.
My log file and settings json: [OpenGOAL-Launcher-config.zip](https://github.com/user-attachments/files/17271592/OpenGOAL-Launcher-config.zip)

### Describe the Bug

Using launcher v2.5.1 AppImage, the page just spins forever.
Using launcher v2.5.0 AppImage, I can correctly see all the tooling versions.

### How To Reproduce

1. Wipe out ~/.config/OpenGOAL-Launcher
2. Download and run v2.5.1 AppImage
3. Set language and installation path
4. Click **Update Available!** next to Tooling
5. Observe how it keeps spinning, and never shows the tooling versions

### Operating System

Arch Linux

### Launcher Version

v2.5.1

### Tooling Version

not set!

**Comment by hypevhs** [comment]
I am able to load the relevant URL in a browser, of course.
https://api.github.com/repos/open-goal/jak-project/releases?per_page=100

**Comment by xTVaser** [comment]
I know what the issue is, ill make a PR with the fix.  What is this bug you are mentioning related to the support-package and wgpu? I see nothing in your logs related to that.

**Comment by hypevhs** [comment]
I opened #588 for the support-package wgpu issue.
