### ISSUE TITLE
downloading verison

### ISSUE THREAD

**Issue by jgatsby347** [open-goal/launcher#587]
When attempting to download the latest version of the files they download with the windows launcher and have the blue dot. it then does not allow me to save the latest version in order to download to play the game. the only icons i see next to this section are the refresh button and file button but no save icon that is shown in the video to download. Please help.

**Comment by xTVaser** [comment]
The save icon was removed a while ago, it automatically saves your version change when you click the radio-button / download a new one.  You can see the number change in the top of the launcher.

![Image](https://github.com/user-attachments/assets/fd4cdc5a-47b0-46db-b072-a2c7e0ba7148)

**Comment by jgatsby347** [comment]
okay understand that how can i access the file name then? when installing via ISO? unsure of the file name to run to download it

**Comment by xTVaser** [comment]
Nothing else has changed (the rest of the tutorial should be accurate), a normal file dialog opens and you select your `.iso` file.  See https://opengoal.dev/docs/usage/installation/#step-1-preparing-your-iso for more information on how to make an ISO from your PS2 disc.

**Comment by jgatsby347** [comment]
thank you
