### ISSUE TITLE
Mod Versions red bubble not rendering properly

### ISSUE THREAD

**Issue by dallmeyer** [open-goal/launcher#597]
From some binary searching, it seems like it broke in this commit https://github.com/open-goal/launcher/commit/9f8e2681b8638ee90cf25df4485fe36c193bfd27, though it's not immediately clear to me why..

This code hasn't really changed, maybe `Indicator` is no longer supported?
https://github.com/open-goal/launcher/blob/eab865c84b94a7f1614bc53021ebffd22d8b3f27/src/components/games/GameControlsMod.svelte#L262-L271

Before:
![Image](https://github.com/user-attachments/assets/665d110b-ab00-4129-af27-348106eb7513)

After:
![Image](https://github.com/user-attachments/assets/151dde89-faa5-4c6c-8d50-e3537476c3c9)

**Comment by xTVaser** [comment]
Potentially related and fixed in a later version https://github.com/themesberg/flowbite-svelte/issues/1452

**Comment by dallmeyer** [comment]
> Potentially related and fixed in a later version [themesberg/flowbite-svelte#1452](https://github.com/themesberg/flowbite-svelte/issues/1452)

Yep, working properly again in v0.47.0
