### ISSUE TITLE
Launcher on the steam deck is not detecting system information correctly

### ISSUE THREAD

**Issue by tvgold42** [open-goal/launcher#60]
Right now when running the launcher on SteamDeck, it does claims the device does not support the appropriate OpenGL version, despite the game running fine on the platform if built from the main repo. Perhaps an 'ignore compatability warning' option could help as a work around for now?

**Comment by xTVaser** [comment]
The launcher hasn't really been tested on the steamdeck as it's theorized it wouldn't be an ideal fit for the platform anyway.  Not to mention the fact that only 1 person in the development team has a steamdeck.  You are likely to run into other issues even if you ignored the requirements check.

I'll leave the issue open but in the long-term I doubt we will be officially supporting the launcher for the steam deck for those reasons.

**Comment by trippjoe** [comment]
@tvgold42 Is this issue still present with the latest version of the launcher?
