### ISSUE TITLE
Unable to download official version

### ISSUE THREAD

**Issue by JFergus98** [open-goal/launcher#619]
### Acknowledgements

- [x] I have [searched](https://github.com/open-goal/launcher/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [x] I understand that I am supposed to provide my own legitimately obtained copy of the game
- [x] If possible, I've attached the support package zip file to the issue [see how here](https://github.com/open-goal/launcher#asking-for-help)

### Attach Support Package / Log Files (drag and drop)

was unable to download the support package, same error. Here are the logs instead
[2024-11-12.log](https://github.com/user-attachments/files/17721598/2024-11-12.log)

### Describe the Bug

I am unable to download and set a tooling version using the launcher. Keep getting this error ![Image](https://github.com/user-attachments/assets/0929e014-8bbf-46af-81cc-c63a426cfab6)

### How To Reproduce

Open the launcher select Tooling, click download on the latest version, error pops up

### Operating System

Window 10

### Launcher Version

v2.5.4

### Tooling Version

Not set

**Comment by xTVaser** [comment]
Looking at your installation directory, it seems like you've picked a location for the launcher that it cannot write files to without elevated admin access (Program Files).

Pick a different installation location that does not require said priveledges, such as your documents folder / desktop and see if that resolves the issue.

**Comment by JFergus98** [comment]
Ah that makes sense, running the launcher as administrator has resolved the problem, thanks
