### ISSUE TITLE
cant find file

### ISSUE THREAD

**Issue by freemuny** [open-goal/launcher#622]
When I open Open goal I can download the version file but when I try and install the iso I cant find the file anywhere on my pc

**Comment by Zedb0T** [comment]
OpenGOAL does not contain the game or any of its assets, it's just a way to play the game if you already own it. You need to extract the iso file from your jak 1 (or 2) disc.

Instructions can be found here: https://opengoal.dev/docs/usage/installation/#step-1-preparing-your-iso
