### ISSUE TITLE
Launcher Not Working

### ISSUE THREAD

**Issue by King-of-Shades** [open-goal/launcher#629]
### Acknowledgements

- [x] I have [searched](https://github.com/open-goal/launcher/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [x] I understand that I am supposed to provide my own legitimately obtained copy of the game
- [x] If possible, I've attached the support package zip file to the issue [see how here](https://github.com/open-goal/launcher#asking-for-help)

### Attach Support Package / Log Files (drag and drop)

Hello. I am NOT a developer, but I was quite confused on how to contact you all and needed some help. I am interested in playing the Jak games natively on PC, so I downloaded the OpenGOAL launcher and it's giving me an error concerning "WebView2". I have tried downloading it from the Microsoft website, but my PC insists it's already installed. Could use some help, thanks!

### Describe the Bug

I am getting an error message saying it crashed. Here is what it says:
unexpected app error occurred:
Runtime(CreateWebview(WebView2Error(WindowsError(Error {code: 0x80070002, message: The system cannot find the file specified. }))))
0: <unknown>
1: <unknown>
2: <unknown>
3: <unknown>
4: <unknown>
5: <unknown>
6: <unknown>
7: <unknown>
8: <unknown>
9: BaseThreadInitThunk
10: RtlUserThreadStart

### How To Reproduce

It happens when I click on the OpenGOAL-Launcher.exe. I have not even gotten to go through the initial setup process yet.

### Operating System

Windows 10

### Launcher Version

OpenGOAL-Launcher 2.5.4

### Tooling Version

Can't even get it to start, so no idea.

**Comment by Zedb0T** [comment]
This error is expected when people uninstall edge/install "debloated" versions of windows.

Go into add remove programs and remove anything webview2 related and grab it from https://developer.microsoft.com/en-us/microsoft-edge/webview2/?cs=608626120&form=MA13LH

Let me know if it works

**Comment by King-of-Shades** [comment]
> This error is expected when people uninstall edge/install "debloated" versions of windows.
> 
> Go into add remove programs and remove anything webview2 related and grab it from https://developer.microsoft.com/en-us/microsoft-edge/webview2/?cs=608626120&form=MA13LH
> 
> Let me know if it works

That fixed it. Thank you!

Also, is there a better way to contact you guys about issues or just with general questions? I tried going to the Discord Help page, and it said there was literally nothing there.

**Comment by Zedb0T** [comment]
Im unsure what you mean by discord help page, but our Discord is typically the best place for end user support
\

Let me know when you have joined so I can remove the link in an edit. Dont want to leave it here for spam bots to scrape.

**Comment by King-of-Shades** [comment]
> Im unsure what you mean by discord help page, but our Discord is typically the best place for end user support
> 
> https://discord.gg/VZbXMHXzWv
> 
> Let me know when you have joined so I can remove the link in an edit. Dont want to leave it here for spam bots to scrape.

Done! Thanks again!
