### ISSUE TITLE
Using launcher it get's stuck 

### ISSUE THREAD

**Issue by AngryScotsmanGaming** [open-goal/launcher#66]
It seems to stick at extracting and validation iso contents a 1/4 of the bar

**Comment by trippjoe** [comment]
> It seems to stick at extracting and validation iso contents a 1/4 of the bar 

This is a known bug that will be fixed in the next release, run as admin until next release.

**Comment by AngryScotsmanGaming** [comment]
thank you for the quick response

**Comment by xTVaser** [comment]
The launcher isn't ready for the public yet, the releases we have put out so far are to help us iron-out the bugs.  I'd advise not using it until we have a `1.0.0` release.

**Comment by trippjoe** [comment]
Fixed with: #65
