### ISSUE TITLE
Possible to have an installation that does not contain goalc at %appdata%\Roaming\OpenGOAL-Launcher\

### ISSUE THREAD

**Issue by Zedb0T** [open-goal/launcher#74]
I've seen this happen to two other people and just verified it on my own machine as well, It might be due to the fact that all of us installed the launcher before the "open REPL" button was implemented, either way with each update the launcher should grab the newest version of goalc and place it in %appdata%\Roaming\OpenGOAL-Launcher\ in case it has been updated/improved

**Comment by xTVaser** [comment]
I don't think the `open REPL` button runs goalc from the appdata folder, and instead runs it from where all the binaries are stored (typically program files) though I'm not 100% sure.

Relevant places are here:
- https://github.com/open-goal/launcher/blob/bcc80553e9877cec5931566e2357cb58b1f553d6/src-tauri/src/commands.rs#L91
- https://github.com/open-goal/launcher/blob/bcc80553e9877cec5931566e2357cb58b1f553d6/src/lib/rpc/commands.ts#L41

**Comment by Zedb0T** [comment]
Placing a copy of goalc into my appdata folder made the button in the launcher work.

(and there is always a copy of it present in program files)
