### ISSUE TITLE
Testing prior to release mega-issue

### ISSUE THREAD

**Issue by xTVaser** [open-goal/launcher#85]
- [x] Test all potential error conditions
- [ ] Does the tauri installer indeed ship with a valid C++ redist
- [ ] Different game versions (NTSC/PAL/etc)
- [x] Test updating procedure
  - works but two things we'll want to fix related to this:
    -  [ ] handle the updating prompt ourselves, the default prompt is kinda ugly AND gets covered up by the launcher window #116
    -  [ ] add release notes to the prompt #117 
- [x] Test updating while playing the game
  - tauri is smart enough (or magic enough) to close the running game.  Perhaps this should be in the prompt though, letting users know a running game will close and to save their progress #116 
- [x] #119

**Comment by Zedb0T** [comment]
Probably hide the Jak 2/3 buttons until they are finished - Its going to lead to alot of "my jak 2 isnt working etc"
Confirmation dialog after selecting "uninstall"

Will update if more ideas cross my mind.
