### ISSUE TITLE
Can't seem to get the launcher open

### ISSUE THREAD

**Issue by UltimateEmboar** [open-goal/launcher#96]
As the title says, can't open the launcher by double clicking on both shortcut and the exe, tried uninstalling and reinstalling but still nothing, how can I fix this? Any replies are greatly appreciated

**Comment by Zedb0T** [comment]
Did you change the installation directory?
Are you on windows or Linux?

**Comment by xTVaser** [comment]
Closing as stale, re-open with more context if the issue persists.
